Beginnings of a working nginx reverse proxy

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -7,10 +7,14 @@ set -o pipefail
 # START CONFIG
 WORDPRESS_VERSION=3.5.1
 HIPHOP_VERSION=2.0.0
+NGINX_VERSION=1.2.6
 DOWNLOAD_TIMEOUT_SEC=3600
+S3_BUCKET=stackato-buildpack-wordpress
 #
 WORDPRESS_URL="http://wordpress.org/wordpress-${WORDPRESS_VERSION}.tar.gz"
+NGINX_URL="https://s3.amazonaws.com/${S3_BUCKET}/nginx-${NGINX_VERSION}.tar.gz"
 HIPHOP_URL="https://dl.dropbox.com/u/33609233/stackato-buildpack-wordpress/hiphop-php-${HIPHOP_VERSION}.tar.gz"
+#PHP_URL="https://s3.amazonaws.com/${S3_BUCKET}/php-${PHP_VERSION}-with-fpm-heroku.tar.gz"
 # END CONFIG
 
 # parse and derive params
@@ -52,8 +56,21 @@ mkdir -p "${BUILD_DIR}/runtimes"
 BUILD_DIR=$(cd "${BUILD_DIR}";pwd) 
 CACHE_DIR=$(cd "${CACHE_DIR}";pwd)
 #
+CACHED_NGINX_DOWNLOAD="${CACHE_DIR}/nginx-${NGINX_VERSION}.tar.gz"
 CACHED_HIPHOP_DOWNLOAD="${CACHE_DIR}/hiphop-php-${HIPHOP_VERSION}.tar.gz"
 CACHED_WORDPRESS_DOWNLOAD="${CACHE_DIR}/wordpress-${WORDPRESS_VERSION}.tar.gz"
+
+echo "-----> Installing NginX v${NGINX_VERSION}"
+if [ ! -f "${CACHED_NGINX_DOWNLOAD}" ]; then
+  echo "Downloading $NGINX_URL to cache: ${CACHED_NGINX_DOWNLOAD}" | indent
+  curl --max-time $DOWNLOAD_TIMEOUT_SEC --location $NGINX_URL > "${CACHED_NGINX_DOWNLOAD}"
+fi
+if [ ! -d "${BUILD_DIR}/runtimes/nginx" ]; then
+   echo "Extracting ${CACHED_NGINX_DOWNLOAD} to ${BUILD_DIR}/runtimes/nginx" | indent
+   tar -xz --directory "${BUILD_DIR}/runtimes" -f "${CACHED_NGINX_DOWNLOAD}"
+else
+  echo "${BUILD_DIR}/runtimes/nginx already configured" | indent
+fi
 
 echo "-----> Installing HipHop v${HIPHOP_VERSION}"
 if [ ! -f "${CACHED_HIPHOP_DOWNLOAD}" ]; then
@@ -96,14 +113,13 @@ echo "Writing setup.sh script" | indent
 cat >bin/setup.sh <<EOF
 #!/usr/bin/env bash
 
-BASE_DIR=\$(cd \$(dirname \$0); cd ..; pwd) # absolute path
-export BASE_DIR
-
 cd "\${BASE_DIR}"
 mkdir -p run/nginx_cache
 
 echo "-----> Writing config files..."
 erb config/hiphop/hhvm.hdf.erb > run/hhvm.hdf
+erb config/nginx/nginx.conf.erb > runtimes/nginx/conf/nginx.conf
+erb config/nginx/wordpress.conf.erb > runtimes/nginx/conf/wordpress.conf
 erb config/wordpress/wp-config.php.erb > public/wp-config.php
 
 chmod 755 public/wp-content
@@ -113,8 +129,11 @@ chmod 755 public/wp-content
 #  echo "env[\$var] = \\$\${var}" >> /app/vendor/php/etc/php-fpm.conf
 #done
 
-mkdir -p logs
-touch logs/access.log logs/error.log 
+mkdir -p \${BASE_DIR}/logs
+touch "\${BASE_DIR}/logs/access.log" "\${BASE_DIR}/logs/error.log"
+echo "-----> Logs are:"
+find "\${BASE_DIR}/logs"  -name *.log
+
 EOF
 chmod +x bin/setup.sh
 
@@ -144,24 +163,41 @@ else
   export LOGLEVEL="Error"
 fi
 
-BASE_DIR=\$(cd \$(dirname \$0); cd ..; pwd) # absolute path
+export PORT_HIPHOP=4242
+
+export BASE_DIR=\$(cd \$(dirname \$0); cd ..; pwd) # absolute path
 echo "-----> BASE_DIR: \${BASE_DIR}"
 cd "\${BASE_DIR}"
 
 bin/setup.sh
 
-echo "-----> Using LOGLEVEL: \$LOGLEVEL [options: None | Error (default) | Warning | Info | Verbose ]"
+echo "-----> Cleanup processes from previous runs"
 killall -q tail 
-(tail -qF -n 0 "\$BASE_DIR/logs/*.log" &)
+killall -q hhvm 
+killall -q nginx 
+killall -q php 
 
-export PATH=\${BASE_DIR/}runtimes/hiphop-php/bin:\$PATH
+# When this exits, exit all back ground process too.
+trap 'kill \$(jobs -p)' EXIT
+
+echo "-----> Using LOGLEVEL: \$LOGLEVEL [options: None | Error (default) | Warning | Info | Verbose ]"
+
+(tail -q -n 0 -F "\${BASE_DIR}/logs/access.log" -F "\${BASE_DIR}/logs/error.log" &)
+
+export PATH=\${BASE_DIR}runtimes/hiphop-php/bin:\$PATH
 export HHVM_LIB_PATH=\$PATH
 export LD_LIBRARY_PATH=\${BASE_DIR}/runtimes/hiphop-php/lib:\${BASE_DIR}/runtimes/hiphop-php/lib/x86_64-linux-gnu:\$LD_LIBRARY_PATH 
 HHVM_BIN="\${BASE_DIR}/runtimes/hiphop-php/bin/hhvm"
+HHVM_VERSION=\$(\${HHVM_BIN} --version | head -n 1)
 
-echo "-----> Starting \$(\${HHVM_BIN} --version)" | head -n 1
-killall -q hhvm 
-"\${HHVM_BIN}" --mode server --config "\$BASE_DIR/run/hhvm.hdf"
+echo "-----> Starting \${HHVM_VERSION} on port \${PORT_HIPHOP}" 
+"\${HHVM_BIN}" --mode daemon --config "\$BASE_DIR/run/hhvm.hdf"
+
+NGINX_BIN="\${BASE_DIR}/runtimes/nginx/sbin/nginx"
+
+echo "-----> Starting \$(\${NGINX_BIN} -v 2>&1) on port \${PORT}" 
+"\${NGINX_BIN}" -p "\${BASE_DIR}/runtimes/nginx"
+
 EOF
 chmod +x bin/start.sh
 
