Cache downloaded assets

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -7,6 +7,7 @@ set -o pipefail
 # START CONFIG
 WORDPRESS_VERSION=3.5.1
 HIPHOP_VERSION=2.0.0
+DOWNLOAD_TIMEOUT_SEC=3600
 #
 WORDPRESS_URL="http://wordpress.org/wordpress-${WORDPRESS_VERSION}.tar.gz"
 HIPHOP_URL="https://dl.dropbox.com/u/33609233/stackato-buildpack-wordpress/hiphop-php-${HIPHOP_VERSION}.tar.gz"
@@ -16,6 +17,24 @@ HIPHOP_URL="https://dl.dropbox.com/u/33609233/stackato-buildpack-wordpress/hipho
 BUILDPACK_DIR=$(cd $(dirname $0); cd ..; pwd) # absolute path of buildpack
 BUILD_DIR=$1
 CACHE_DIR=$2
+HELP=$'\e[1;33m=-=-=-=-= bin/compile =-=-=-=-=\nAdd WP Core files, HipHop-PHP runtime and configuration to files in <build-dir> so they can be served by Stackato.\nDownloaded assets are cached in <cache-dir>.\nMust be called like this:\nbin/compile <build-dir> <cache-dir>\e[00m'
+if [[ -z "$BUILD_DIR" ]]; then
+  echo -e "\e[00;31mError: You must pass a valid <build-dir>"
+  echo -e "$HELP"
+  exit 1
+fi
+if [ ! -d $BUILD_DIR/public/wp-content ]; then
+  echo -e "\e[00;31mError: $BUILD_DIR/public/wp-content must exist and contain your wordpress themes & plugins"
+  echo -e "$HELP"
+  exit 1
+fi
+if [[ -z "$CACHE_DIR" ]]; then
+  echo -e "\e[00;31mError: You must pass a valid <cache-dir>"
+  echo -e "$HELP"
+  exit 1
+fi
+CACHED_HIPHOP_DOWNLOAD="${CACHE_DIR}/hiphop-php-${HIPHOP_VERSION}.tar.gz"
+CACHED_WORDPRESS_DOWNLOAD="${CACHE_DIR}/wordpress-${WORDPRESS_VERSION}.tar.gz"
 
 echo "-----> compile params: BUILDPACK_DIR: $BUILDPACK_DIR BUILD_DIR: $BUILD_DIR CACHE_DIR:$CACHE_DIR"
 
@@ -27,24 +46,39 @@ function indent() {
   esac
 }
 
-cd ${BUILD_DIR}
-mkdir -p runtimes
+mkdir -p $CACHE_DIR
+#normalize paths
+BUILD_DIR=$(cd "${BUILD_DIR}";pwd) 
+CACHE_DIR=$(cd "${CACHE_DIR}";pwd)
+mkdir -p $BUILD_DIR/runtimes
+
 echo "-----> Installing HipHop v${HIPHOP_VERSION}"
-if [ ! -d ./runtimes/hiphop-php ]; then
-  cd ./runtimes
-  curl --max-time 3600 --location $HIPHOP_URL | tar -xzv
+if [ ! -f $CACHED_HIPHOP_DOWNLOAD  ]; then
+  echo "Downloading $HIPHOP_URL to cache: $CACHED_HIPHOP_DOWNLOAD" | indent
+  curl --max-time $DOWNLOAD_TIMEOUT_SEC --location --output $CACHED_HIPHOP_DOWNLOAD $HIPHOP_URL
+fi
+if [ ! -d $BUILD_DIR/runtimes/hiphop-php ]; then
+   echo "Extracting $CACHED_HIPHOP_DOWNLOAD to $BUILD_DIR/runtimes/hiphop-php" | indent
+   tar -xz --directory $BUILD_DIR/runtimes -f $CACHED_HIPHOP_DOWNLOAD
+else
+  echo "$BUILD_DIR/runtimes/hiphop-php already configured" | indent
 fi
 
-cd ${BUILD_DIR}
 echo "-----> Installing WordPress v${WORDPRESS_VERSION}"
-if [ ! -d ./public/wordpress ]; then
-  cd ./public/
-  curl --max-time 3600 --location $WORDPRESS_URL | tar -xzv
+if [ ! -f $CACHED_WORDPRESS_DOWNLOAD  ]; then
+  echo "Downloading $WORDPRESS_URL to cache: $CACHED_WORDPRESS_DOWNLOAD" | indent
+  curl --max-time $DOWNLOAD_TIMEOUT_SEC --location --output $CACHED_WORDPRESS_DOWNLOAD $WORDPRESS_URL
+fi
+if [ ! -d $BUILD_DIR/public/wordpress ]; then
+  echo "Extracting $CACHED_WORDPRESS_DOWNLOAD to $BUILD_DIR/public/wordpress" | indent
+  tar -xz --directory $BUILD_DIR/public -f $CACHED_WORDPRESS_DOWNLOAD
   echo "Patching WordPress source to make it HipHop compliant" | indent
   sed --in-place --expression \
     "s|define( 'OBJECT', 'OBJECT', true );|define('OBJECT', 'OBJECT'); define('Object', 'OBJECT'); define('object', 'OBJECT');|g" \
-    wordpress/wp-includes/wp-db.php
-  echo "<?php define('WP_USE_THEMES', true); require('./wordpress/wp-blog-header.php');" > index.php
+    $BUILD_DIR/public/wordpress/wp-includes/wp-db.php
+  echo "<?php define('WP_USE_THEMES', true); require('./wordpress/wp-blog-header.php');" > $BUILD_DIR/public/index.php
+else
+  echo "$BUILD_DIR/public/wordpress already configured" | indent
 fi
 
 echo "-----> Copying config templates"
