Copy archived assets to BUILDPACK_CACHE folder

diff --git a/support/package_hiphop b/support/package_hiphop
--- a/support/package_hiphop
+++ b/support/package_hiphop
@@ -1,7 +1,8 @@
 #!/bin/bash
-echo "This is a work in progress, and doesn't currently work :("
-
-exit 1
+if [[ -z "$BUILDPACK_CACHE" ]]; then
+  echo -e "\e[00;31mError: Must pass a valid BUILDPACK_CACHE - eg: BUILDPACK_CACHE=~/.buildpack-cache"
+  exit 1
+fi
 
 sudo apt-get update 
 sudo apt-get purge libboost*1.46* -y
@@ -173,3 +174,7 @@ tree ${PACKAGE_DIR}
 
 echo "-----> Creating archive: hiphop-php-2.1.0-dev.tar.gz"
 tar --transform='s,^tmp/,,' -czf hiphop-php-2.1.0-dev.tar.gz ${PACKAGE_DIR}/
+
+mv $(pwd)/hiphop-php-2.1.0-dev.tar.gz ${BUILDPACK_CACHE}
+
+echo "Successfully finished building nginx to ${BUILDPACK_CACHE}/hiphop-php-2.1.0-dev.tar.gz"
diff --git a/support/package_nginx b/support/package_nginx
--- a/support/package_nginx
+++ b/support/package_nginx
@@ -3,7 +3,12 @@
 set -e
 
 if [ -z "$NGINX_VERSION" ]; then
-  echo "must set NGINX_VERSION, i.e NGINX_VERSION=1.2.6"
+  echo -e "\e[00;31mError: Must set NGINX_VERSION, i.e NGINX_VERSION=1.2.6"
+  exit 1
+fi
+
+if [[ -z "$BUILDPACK_CACHE" ]]; then
+  echo -e "\e[00;31mError: Must pass a valid BUILDPACK_CACHE - eg: BUILDPACK_CACHE=~/.buildpack-cache"
   exit 1
 fi
 
@@ -40,24 +45,6 @@ pushd $tempdir/nginx-$NGINX_VERSION
 popd
 tar --transform='s,^app/runtimes/,,' -czf nginx-$NGINX_VERSION.tar.gz /app/runtimes/nginx/
 
-echo "Successfully finished building nginx to $(pwd)/nginx-$NGINX_VERSION.tar.gz"
+mv $(pwd)/nginx-$NGINX_VERSION.tar.gz ${BUILDPACK_CACHE}
 
-# upload to s3
-echo "Now uploading it to S3"
-
-if [ -z "$AWS_ID" ]; then
-  echo "must set AWS_ID, i.e. export AWS_ID=1BHAJK48DJFMQKZMNV93"
-  exit 1
-fi
-
-if [ -z "$AWS_SECRET" ]; then
-  echo "must set AWS_SECRET, i.e. export AWS_SECRET=fj2jjchebsjksmMJCN387RHNjdnddNfi4jjhshh3"
-  exit 1
-fi
-
-if [ -z "$S3_BUCKET" ]; then
-  echo "must set S3_BUCKET, i.e. S3_BUCKET=heroku-buildpack-wordpress"
-  exit 1
-fi
-
-$basedir/aws/s3 put $S3_BUCKET nginx-$NGINX_VERSION.tar.gz $tempdir/nginx-$NGINX_VERSION.tar.gz
+echo "Successfully finished building nginx to ${BUILDPACK_CACHE}/nginx-$NGINX_VERSION.tar.gz"
diff --git a/support/package_php b/support/package_php
--- a/support/package_php
+++ b/support/package_php
@@ -3,11 +3,14 @@
 set -e
 
 if [ -z "$PHP_VERSION" ]; then
-  echo "must set PHP_VERSION, i.e PHP_VERSION=5.4.14"
+  echo -e "\e[00;31mError: Must set PHP_VERSION, i.e PHP_VERSION=5.4.14"
   exit 1
 fi
 
-BUILDPACK_CACHE=~/.buildpack-cache
+if [[ -z "$BUILDPACK_CACHE" ]]; then
+  echo -e "\e[00;31mError: Must pass a valid BUILDPACK_CACHE - eg: BUILDPACK_CACHE=~/.buildpack-cache"
+  exit 1
+fi
 
 sudo apt-get install libcurl4-openssl-dev pkg-config libbz2-dev libjpeg-dev libpng-dev -y
 
